// Calendário Oficial League Two 24/25 Compactado (Exatamente igual às imagens)
const rawSchedule = [
    "CHF-SWI,WIM-COL,BAW-CRE,CHE-NWP,DON-ACC,FLE-GRI,GIL-CAR,HAR-BRO,MKD-BRA,SAL-PTV,TRA-NOT,WAL-MOR", // J1
    "BRO-WIM,CAR-BAW,ACC-HAR,BRA-SAL,COL-MKD,CRE-CHF,GRI-CHE,MOR-GIL,NWP-DON,PTV-TRA,SWI-WAL,NOT-FLE", // J2
    "NOT-GRI,CRE-SWI,TRA-WAL,BAW-PTV,BRA-BRO,CHE-WIM,CHF-SAL,COL-HAR,DON-MOR,FLE-GIL,MKD-CAR,NWP-ACC", // J3
    "GIL-CHF,WIM-FLE,ACC-COL,BRO-CRE,CAR-TRA,GRI-BRA,HAR-BAW,MOR-NWP,SWI-NOT,WAL-CHE,SAL-MKD,PTV-DON", // J4
    "BAW-SWI,BRA-CAR,CHE-HAR,CHF-GRI,COL-BRO,CRE-MOR,DON-GIL,MKD-WAL,NWP-PTV,NOT-ACC,FLE-SAL,TRA-WIM", // J5
    "HAR-DON,WIM-MKD,SWI-NWP,ACC-CRE,BRO-NOT,CAR-FLE,GIL-TRA,GRI-BAW,MOR-COL,PTV-CHF,SAL-CHE,WAL-BRA", // J6
    "ACC-PTV,CHF-CHE,BAW-NWP,BRA-WIM,COL-TRA,CRE-HAR,GRI-BRO,MKD-DON,NOT-GIL,SAL-WAL,SWI-CAR,FLE-MOR", // J7
    "TRA-SAL,HAR-BRA,WAL-COL,BRO-MKD,CAR-GRI,CHE-FLE,DON-CHF,GIL-BAW,MOR-NOT,NWP-CRE,PTV-SWI,WIM-ACC", // J8
    "BRO-CHF,CAR-NOT,CHE-ACC,DON-BAW,GIL-GRI,HAR-MKD,MOR-BRA,PTV-COL,TRA-SWI,WAL-FLE,NWP-SAL,WIM-CRE", // J9
    "FLE-BRO,GRI-DON,BAW-CHE,CHF-WAL,COL-CAR,CRE-GIL,MKD-TRA,NOT-PTV,SAL-WIM,SWI-HAR,ACC-MOR,BRA-NWP", // J10
    "CHF-NOT,GIL-ACC,MKD-PTV,SAL-GRI,TRA-BRA,HAR-NWP,DON-CRE,CHE-SWI,BAW-MOR,WIM-CAR,WAL-BRO,FLE-COL", // J11
    "NWP-CHF,ACC-BAW,BRA-GIL,BRO-TRA,COL-CHE,CRE-SAL,GRI-WAL,MOR-MKD,NOT-WIM,PTV-FLE,SWI-DON,CAR-HAR", // J12
    "GIL-NWP,WIM-MOR,TRA-GRI,SAL-SWI,MKD-ACC,HAR-PTV,FLE-CRE,DON-BRO,CHF-COL,CHE-BRA,BAW-NOT,WAL-CAR", // J13
    "MOR-CHF,COL-SAL,NWP-FLE,NOT-HAR,GRI-MKD,CRE-TRA,CAR-CHE,BRO-BAW,BRA-DON,ACC-WAL,PTV-WIM,SWI-GIL", // J14
    "SAL-CAR,HAR-MOR,TRA-NWP,WAL-CRE,GIL-PTV,FLE-BRA,DON-NOT,CHF-ACC,CHE-BRO,BAW-COL,WIM-GRI,MKD-SWI", // J15
    "NWP-GRI,MKD-CHE,MOR-PTV,HAR-CHF,DON-SAL,CRE-NOT,COL-BRA,BRO-CAR,BAW-WIM,ACC-SWI,WAL-GIL,TRA-FLE", // J16
    "CHE-TRA,NOT-NWP,GRI-COL,CHF-BAW,CAR-DON,WIM-WAL,GIL-HAR,SWI-MOR,PTV-CRE,FLE-MKD,SAL-BRO,BRA-ACC", // J17
    "CAR-CRE,WIM-NWP,GRI-ACC,MKD-CHF,SAL-HAR,TRA-MOR,WAL-NOT,BRA-BAW,CHE-PTV,COL-SWI,BRO-GIL,FLE-DON", // J18
    "CRE-BRA,PTV-WAL,ACC-BRO,CHF-TRA,DON-CHE,GIL-SAL,HAR-WIM,MOR-GRI,SWI-FLE,NWP-CAR,BAW-MKD,NOT-COL", // J19
    "TRA-HAR,SAL-NOT,COL-NWP,CAR-CHF,WAL-BAW,MKD-GIL,GRI-CRE,CHE-MOR,WIM-DON,BRA-SWI,BRO-PTV,FLE-ACC", // J20
    "GIL-CHE,CRE-COL,DON-TRA,BAW-FLE,NWP-MKD,SWI-GRI,PTV-CAR,NOT-BRA,MOR-BRO,HAR-WAL,ACC-SAL,CHF-WIM", // J21
    "BRO-NWP,WIM-SWI,BRA-PTV,WAL-DON,SAL-BAW,MKD-NOT,GRI-HAR,FLE-CHF,COL-GIL,CHE-CRE,CAR-MOR,TRA-ACC", // J22
    "CAR-ACC,BRO-SWI,WAL-NWP,TRA-BAW,SAL-MOR,MKD-CRE,GRI-PTV,FLE-HAR,COL-DON,CHE-NOT,BRA-CHF,WIM-GIL", // J23
    "SWI-COL,NOT-WAL,MOR-TRA,HAR-SAL,DON-FLE,CRE-CAR,CHF-MKD,BAW-BRA,ACC-GRI,PTV-CHE,NWP-WIM,GIL-BRO", // J24
    "NOT-SWI,BRA-GRI,DON-PTV,COL-ACC,BAW-HAR,MKD-SAL,TRA-CAR,CRE-BRO,NWP-MOR,FLE-WIM,CHE-WAL,CHF-GIL", // J25
    "WAL-TRA,SWI-CRE,HAR-COL,MOR-DON,GIL-FLE,BRO-BRA,ACC-NWP,SAL-CHF,GRI-NOT,WIM-CHE,PTV-BAW,CAR-MKD", // J26
    "HAR-CHE,GIL-DON,CAR-BRA,PTV-NWP,MOR-CRE,SAL-FLE,SWI-BAW,WAL-MKD,GRI-CHF,BRO-COL,ACC-NOT,WIM-TRA", // J27
    "NWP-SWI,BRA-WAL,MKD-WIM,BAW-GRI,CHE-SAL,CHF-PTV,CRE-ACC,DON-HAR,FLE-CAR,NOT-BRO,TRA-GIL,COL-MOR", // J28
    "SAL-NWP,CRE-WIM,FLE-WAL,GRI-GIL,MKD-HAR,NOT-CAR,SWI-TRA,CHF-BRO,ACC-CHE,BRA-MOR,BAW-DON,COL-PTV", // J29
    "GIL-NOT,CHE-CHF,NWP-BAW,WAL-SAL,TRA-COL,PTV-ACC,MOR-FLE,DON-MKD,CAR-SWI,BRO-GRI,WIM-BRA,HAR-CRE", // J30
    "CHF-DON,BRA-HAR,SWI-PTV,CRE-NWP,COL-WAL,BAW-GIL,ACC-WIM,FLE-CHE,SAL-TRA,NOT-MOR,MKD-BRO,GRI-CAR", // J31
    "PTV-NOT,WIM-SAL,DON-GRI,NWP-BRA,WAL-CHF,TRA-MKD,MOR-ACC,HAR-SWI,GIL-CRE,CHE-BAW,CAR-COL,BRO-FLE", // J32
    "MOR-WAL,CRE-BAW,NWP-CHE,CAR-GIL,SWI-CHF,PTV-SAL,NOT-TRA,GRI-FLE,COL-WIM,BRO-HAR,BRA-MKD,ACC-DON", // J33
    "BAW-CAR,TRA-PTV,SAL-BRA,DON-NWP,WAL-SWI,MKD-COL,HAR-ACC,GIL-MOR,FLE-NOT,CHF-CRE,WIM-BRO,CHE-GRI", // J34
    "NWP-GIL,ACC-MKD,BRA-CHE,SWI-SAL,PTV-HAR,NOT-BAW,MOR-WIM,GRI-TRA,CRE-FLE,COL-CHF,CAR-WAL,BRO-DON", // J35
    "WAL-GRI,WIM-NOT,CHF-NWP,TRA-BRO,SAL-CRE,MKD-MOR,HAR-CAR,GIL-BRA,FLE-PTV,DON-SWI,CHE-COL,BAW-ACC", // J36
    "BRO-WAL,CRE-DON,SWI-CHE,NWP-HAR,MOR-BAW,GRI-SAL,COL-FLE,CAR-WIM,BRA-TRA,PTV-MKD,NOT-CHF,ACC-GIL", // J37
    "NOT-CRE,GRI-NWP,SWI-ACC,WIM-BAW,BRA-COL,CAR-BRO,CHE-MKD,CHF-HAR,FLE-TRA,GIL-WAL,PTV-MOR,SAL-DON", // J38
    "COL-GRI,TRA-CHE,ACC-BRA,CRE-PTV,NWP-NOT,BAW-CHF,BRO-SAL,DON-CAR,HAR-GIL,MKD-FLE,MOR-SWI,WAL-WIM", // J39
    "NWP-BRO,HAR-TRA,MOR-CHE,PTV-BRA,SWI-WIM,ACC-FLE,BAW-SAL,CHF-CAR,CRE-GRI,DON-WAL,GIL-COL,NOT-MKD", // J40
    "CHE-DON,WAL-PTV,TRA-CHF,CAR-NWP,WIM-HAR,BRA-CRE,BRO-ACC,COL-NOT,FLE-SWI,GRI-MOR,MKD-BAW,SAL-GIL", // J41
    "CRE-CHE,NOT-SAL,DON-WIM,SWI-BRA,NWP-COL,ACC-TRA,BAW-WAL,CHF-FLE,GIL-MKD,HAR-GRI,MOR-CAR,PTV-BRO", // J42
    "BRA-NOT,MKD-NWP,WAL-HAR,TRA-DON,SAL-ACC,GRI-SWI,FLE-BAW,COL-CRE,CHE-GIL,CAR-PTV,BRO-MOR,WIM-CHF", // J43
    "NWP-WAL,CHF-BRA,SWI-BRO,PTV-GRI,NOT-CHE,MOR-SAL,HAR-FLE,GIL-WIM,DON-COL,CRE-MKD,BAW-TRA,ACC-CAR", // J44
    "DON-BRA,WIM-PTV,HAR-NOT,FLE-NWP,WAL-ACC,TRA-CRE,SAL-COL,MKD-GRI,GIL-SWI,CHF-MOR,CHE-CAR,BAW-BRO", // J45
    "NWP-TRA,ACC-CHF,PTV-GIL,NOT-DON,MOR-HAR,GRI-WIM,CRE-WAL,COL-BAW,CAR-SAL,BRO-CHE,BRA-FLE,SWI-MKD"  // J46
];

export const schedule = [];

rawSchedule.forEach((roundString, roundIndex) => {
    const matches = roundString.split(',');
    matches.forEach((match, matchIndex) => {
        const [home, away] = match.split('-');
        schedule.push({
            id: `r${roundIndex + 1}m${matchIndex + 1}`,
            round: roundIndex + 1,
            home: home,
            away: away
        });
    });
});